services:
  - type: web
    name: sns-app
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn snsproject.wsgi:application'
    plan: free
    branch: master
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: 4

      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

    autoDeploy: true