services:
  - type: web
    name: sns-app
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn snsproject.wsgi:application'
    plan: free
    branch: master
    healthCheckPath: /admin/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supabase-external
          property: connectionString
      - key: SECRET_KEY
        sync: false  

    autoDeploy: true