services:
  - type: web
    name: sns-app
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn snsproject.wsgi:application'
    plan: free
    branch: master
    healthCheckPath: /admin/
    envVars:
      envVars:
      - key: DATABASE_URL
        sync: false

      - key: SECRET_KEY
        generateValue: true

      - key: WEB_CONCURRENCY
        value: 4

    autoDeploy: true