# Generated by Django 5.0.4 on 2025-04-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=100)),
                ('read', models.IntegerField(blank=True, default=1, null=True)),
                ('good', models.IntegerField(blank=True, default=1, null=True)),
                ('readers', models.TextField(blank=True, default='a', null=True)),
            ],
        ),
    ]
